### ISSUE TITLE
Sampling

### ISSUE THREAD

**Issue by khosravipasha** [Juice-jl/pyjuice#5]
After merging #4, there is few things left:

- [x] Still Few or the pixels seems to have 0 flow on all input nodes for that pixel, the sum of flows for each variable input nodes should be exactly 1. 
- [x] Sampling for categorical layers assumes same cateogory count for all features (e.g. 256 categories for mnist), to handle other cases probably need to write a triton kernel.
- [x] [Potential Speed when a lot of samples needed]. Right now does one sample per item in batch based on missing_maks, if want a lot of samples for sample multiple times on the same batch. Can probably do something similar to Juice.jl to do all samples at the same time.

**Comment by liuanji** [comment]
For the second problem, we can build separate input layers for input nodes with different category counts. I will look into this.

**Comment by liuanji** [comment]
fixed in the refactored version; see https://github.com/Juice-jl/pyjuice/blob/bf8e3aed6b8b91b73f87f2c3ebeb65cbf19a3e46/src/pyjuice/queries/sample.py#L72
