### ISSUE TITLE
Examples are broken with module 'pyjuice' has no attribute 'ProbCircuit'

### ISSUE THREAD

**Issue by KareemYousrii** [Juice-jl/pyjuice#7]
It seems the examples are using an outdated API where `ProbCircuit` was replaced with `TensorCircuit`? But even then, changing all occurrences of `ProbCircuit` to `TensorCircuit` leads to other errors where after calling `pc = juice.model.TensorCircuit.load(filename)`, a call to `pc.to(device)` returns an `AttributeError: 'SumNodes' object has no attribute 'to'` error. This occurs when attempting to run `examples/1_pc_training/train_mnist_hclt.py`.

**Comment by liuanji** [comment]
Fixed in the latest release
